name: dMRIpyTorch
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - tensorboard
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - scipy
  - ipykernel
  - ignite
  - scikit-learn
  - feature_engine
  - statsmodels
  - mlxtend
  - tqdm
  - opencv
  - jupyterlab
  - notebook
  - voila
  - nibabel
  - nilearn
