batch_size: 16
learning_rate: 1.0e-05
multiplier: 20
num_workers: 8
scheduler_gamma: 0.3
scheduler_step_size: 25
study_path: ../../study
test_subjs_idx:
- 2
- 16
- 13
- 12
val_subjs_idx:
- 0
- 7
- 10
- 14
