batch_size: 2
learning_rate: 0.001
multiplier: 20
num_workers: 10
scheduler_gamma: 100
scheduler_step_size: 0.1
study_path: ../../study
test_subjs_idx:
- 2
- 16
- 13
- 12
val_subjs_idx:
- 0
- 7
- 10
- 14
