name: dMRI
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - tensorboard
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - scipy
  - ipykernel
  - ipython
  - ipywidgets
  - ignite
  - scikit-learn
  - feature_engine
  - statsmodels
  - mlxtend
  - tqdm
  - opencv
  - jupyterlab
  - notebook
  - voila
  - nibabel
  - nilearn
  - pip
  - monai
  - lightning
  - torchmetrics
  - ants
  - ipympl
  - dipy
  - pypdf
  - fpdf
  - pip:
    - torchio
    - ITMO-FS
    - antspyx
