batch_size: 32
learning_rate: 1.0e-06
multiplier: 8
num_workers: 10
scheduler_gamma: 0.1
scheduler_step_size: 200
study_path: ../../study
test_subjs_idx:
- 2
- 16
- 13
- 12
val_subjs_idx:
- 0
- 7
- 10
- 14
