batch_size: 16
learning_rate: 0.0001
multiplier: 20
num_workers: 8
scheduler_gamma: 0.1
scheduler_step_size: 7
study_path: ../../study
test_subjs_idx:
- 2
- 16
- 13
- 12
val_subjs_idx:
- 0
- 7
- 10
- 14
