#!/bin/bash
#
#SBATCH --job-name=seg
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=michele.cerra@student.uclouvain.be
#SBATCH --output=seg_out.txt
#SBATCH --error=seg_err.txt
#
#SBATCH --cpus-per-task=4
#SBATCH --time=0
#SBATCH --time-min=10:0:0
#SBATCH --mem-per-cpu=4000

module load freesurfer
export SUBJECTS_DIR=~/Epilepsy-dMRI-VNS/seg_subjs
# doesn't work, i should add the -force.., beacuse it's already generated by the recon-all
srun --cpus-per-task=4 mri_cc -aseg $SUBJECTS_DIR/subj00/mri/aseg.mgz -o $SUBJECTS_DIR/subj00/mri/aseg.auto_CCseg.mgz -f subj00 